"""言語設定モジュール — Language state and UI string translations"""

LANG: str = "ja"

CATEGORIES: dict[str, dict[str, str]] = {
    "ja": {
        "file":    "📁 ファイル操作",
        "text":    "📝 テキスト処理",
        "process": "⚙️  プロセス管理",
        "network": "🌐 ネットワーク",
        "shell":   "🐚 シェル・環境",
        "system":  "💻 システム情報",
    },
    "en": {
        "file":    "📁 File Operations",
        "text":    "📝 Text Processing",
        "process": "⚙️  Process Management",
        "network": "🌐 Networking",
        "shell":   "🐚 Shell & Environment",
        "system":  "💻 System Info",
    },
}

_STRINGS: dict[str, dict[str, str]] = {
    "ja": {
        "lang_select_title": "言語を選んでください",
        "lang_ja":           "日本語",
        "lang_en":           "English",
        "menu_title":        "メニュー",
        "menu_1":            "📚 教科書で学ぶ   — 解説を読んで実際に試す",
        "menu_2":            "📝 クイズで練習する — カテゴリ別 / ランダム出題",
        "menu_3":            "📖 コマンド一覧を見る",
        "menu_4":            "📊 学習進捗を確認する",
        "menu_quit":         "終了",
        "menu_back":         "戻る",
        "menu_enter":        "Enter",
        "invalid_input":     "無効な入力です。",
        "choose":            "選択",
        "press_enter":       "Enter キーで続ける...",
        "farewell":          "\n  お疲れさまでした！また学習しましょう。\n",
        "menu_invalid_range":"1〜4 または q を入力してください。",
        "difficulty_prompt": "難易度を選んでください:",
        "diff_easy":         "易  ★☆☆",
        "diff_med":          "中  ★★☆",
        "diff_hard":         "難  ★★★",
        "diff_all":          "すべて",
        "quiz_category":     "📝 カテゴリ別クイズ",
        "quiz_random":       "🔀 ランダム出題",
        "quiz_practice":     "📝 クイズで練習する",
        "quiz_cat_label":    "カテゴリ別クイズ",
        "quiz_rand_label":   "ランダム出題（全カテゴリ）",
        "quiz_rand_title":   "ランダムクイズ",
        "quiz_no_diff":      "その難易度の問題はありません。",
        "quiz_no_match":     "該当する問題がありません。",
        "quiz_invalid_menu": "1・2・0 のいずれかを入力してください。",
        "cmd_list_header":   "📖 コマンド一覧",
        "progress_header":   "📊 学習進捗",
        "progress_cat_col":  "  カテゴリ",
        "progress_tb_col":   "教科書",
        "progress_qz_col":   "クイズ正答率",
        "progress_not_taken":"未受験",
        "progress_total":    "合計",
        "progress_last_updated": "最終更新: {ts}",
        "progress_reset_label":  "進捗をリセットする",
        "progress_reset_header": "⚠️  進捗リセット",
        "progress_reset_warn1":  "教科書の完了記録とクイズの回答履歴がすべて削除されます。",
        "progress_reset_warn2":  "この操作は元に戻せません。",
        "progress_reset_confirm":"本当にリセットしますか？ [yes でリセット / その他でキャンセル]",
        "progress_reset_done":   "  ✓ 進捗をリセットしました。",
        "progress_cancel":       "  キャンセルしました。",
        "question_label":    "問題 {n}/{total}",
        "correct":           "  ✓ 正解！",
        "wrong":             "  ✗ 不正解",
        "correct_ans":       "  正解: {ans}",
        "results_header":    "結果",
        "score_correct":     "正解数",
        "score_rate":        "正答率",
        "score_great":       "  素晴らしい！",
        "score_almost":      "  もう少し！復習してみよう",
        "score_basic":       "  基礎から確認しよう",
        "tb_header":         "📚 教科書で学ぶ",
        "tb_subtitle":       "コマンドの解説を読み、実際に試してみよう！",
        "tb_lesson_list":    "  —  レッスン一覧",
        "tb_legend":         "✓=完了  →=開始済み  ○=未開始",
        "tb_desc":           "  📖 説明",
        "tb_syntax":         "  📋 構文",
        "tb_options":        "  ⚙️  主なオプション",
        "tb_example":        "  例 {n}/{total}",
        "tb_run_prompt":     "[r] 実行する  [s] スキップ  [q] レッスン終了",
        "tb_sim_hdr":        "  ─── 出力イメージ ─────────────────────────",
        "tb_run_hdr":        "  ─── 実行結果 ────────────────────────────",
        "tb_divider":        "  ─────────────────────────────────────────",
        "tb_no_output":      "(出力なし)",
        "tb_timeout":        "(タイムアウト: 10秒以内に完了しませんでした)",
        "tb_complete":       "  ✓ レッスン完了！進捗が更新されました。",
        "qe_choice_prompt":  "A/B/C/D を入力",
        "qe_choice_invalid": "  A, B, C, D のいずれかを入力してください。",
        "qe_fill_prompt":    "コマンドを入力してください",
        "qe_results":        " — 結果",
    },
    "en": {
        "lang_select_title": "Select Language",
        "lang_ja":           "日本語",
        "lang_en":           "English",
        "menu_title":        "Menu",
        "menu_1":            "📚 Textbook   — Read explanations and try commands",
        "menu_2":            "📝 Quiz   — By category / Random",
        "menu_3":            "📖 Command List",
        "menu_4":            "📊 Learning Progress",
        "menu_quit":         "Quit",
        "menu_back":         "Back",
        "menu_enter":        "Enter",
        "invalid_input":     "Invalid input.",
        "choose":            "Choice",
        "press_enter":       "Press Enter to continue...",
        "farewell":          "\n  Great work! Come back and study again.\n",
        "menu_invalid_range":"Please enter 1–4 or q.",
        "difficulty_prompt": "Select difficulty:",
        "diff_easy":         "Easy  ★☆☆",
        "diff_med":          "Med   ★★☆",
        "diff_hard":         "Hard  ★★★",
        "diff_all":          "All",
        "quiz_category":     "📝 Quiz by Category",
        "quiz_random":       "🔀 Random Quiz",
        "quiz_practice":     "📝 Practice Quiz",
        "quiz_cat_label":    "Quiz by Category",
        "quiz_rand_label":   "Random Quiz (All Categories)",
        "quiz_rand_title":   "Random Quiz",
        "quiz_no_diff":      "No questions for that difficulty.",
        "quiz_no_match":     "No matching questions.",
        "quiz_invalid_menu": "Please enter 1, 2, or 0.",
        "cmd_list_header":   "📖 Command List",
        "progress_header":   "📊 Learning Progress",
        "progress_cat_col":  "  Category",
        "progress_tb_col":   "Textbook",
        "progress_qz_col":   "Quiz Score",
        "progress_not_taken":"Not taken",
        "progress_total":    "Total",
        "progress_last_updated": "Last updated: {ts}",
        "progress_reset_label":  "Reset Progress",
        "progress_reset_header": "⚠️  Reset Progress",
        "progress_reset_warn1":  "All textbook and quiz records will be permanently deleted.",
        "progress_reset_warn2":  "This cannot be undone.",
        "progress_reset_confirm":"Reset? [type yes / other key to cancel]",
        "progress_reset_done":   "  ✓ Progress has been reset.",
        "progress_cancel":       "  Cancelled.",
        "question_label":    "Question {n}/{total}",
        "correct":           "  ✓ Correct!",
        "wrong":             "  ✗ Wrong",
        "correct_ans":       "  Answer: {ans}",
        "results_header":    "Results",
        "score_correct":     "Correct",
        "score_rate":        "Score",
        "score_great":       "  Excellent!",
        "score_almost":      "  Almost there! Review and try again.",
        "score_basic":       "  Let's go back to basics.",
        "tb_header":         "📚 Textbook",
        "tb_subtitle":       "Read command explanations and try them yourself!",
        "tb_lesson_list":    "  —  Lessons",
        "tb_legend":         "✓=Done  →=Started  ○=Not started",
        "tb_desc":           "  📖 Description",
        "tb_syntax":         "  📋 Syntax",
        "tb_options":        "  ⚙️  Key Options",
        "tb_example":        "  Example {n}/{total}",
        "tb_run_prompt":     "[r] Run  [s] Skip  [q] Quit Lesson",
        "tb_sim_hdr":        "  ─── Expected Output ────────────────────",
        "tb_run_hdr":        "  ─── Output ──────────────────────────────",
        "tb_divider":        "  ─────────────────────────────────────────",
        "tb_no_output":      "(no output)",
        "tb_timeout":        "(Timeout: did not complete within 10 seconds)",
        "tb_complete":       "  ✓ Lesson complete! Progress updated.",
        "qe_choice_prompt":  "Enter A/B/C/D",
        "qe_choice_invalid": "  Please enter A, B, C, or D.",
        "qe_fill_prompt":    "Enter the command",
        "qe_results":        " — Results",
    },
}


def set_lang(code: str) -> None:
    global LANG
    LANG = code


def get_categories() -> dict[str, str]:
    return CATEGORIES[LANG]


def t(key: str, **kwargs: str) -> str:
    text = _STRINGS.get(LANG, _STRINGS["ja"]).get(key)
    if text is None:
        text = _STRINGS["ja"].get(key, key)
    return text.format(**kwargs) if kwargs else text
