"""問題データベース（日本語）"""

from typing import TypedDict


class Question(TypedDict):
    id: str
    category: str
    difficulty: int
    type: str
    question: str
    choices: list[str]
    answer: str
    explanation: str


QUESTIONS: list[Question] = [

    # ══════════════════════════════════════════════════════════
    # 📁 ファイル操作
    # ══════════════════════════════════════════════════════════
    {"id": "file_01", "category": "file", "difficulty": 1, "type": "choice",
     "question": "現在のディレクトリにあるファイルを一覧表示するコマンドは？",
     "choices": ["ls", "cd", "pwd", "cat"], "answer": "ls",
     "explanation": "ls (list) はディレクトリの内容を一覧表示します。"},
    {"id": "file_02", "category": "file", "difficulty": 1, "type": "choice",
     "question": "現在いる場所（カレントディレクトリ）のパスを表示するコマンドは？",
     "choices": ["pwd", "ls", "cd", "echo"], "answer": "pwd",
     "explanation": "pwd (print working directory) で現在のパスが表示されます。"},
    {"id": "file_03", "category": "file", "difficulty": 1, "type": "fill",
     "question": "ホームディレクトリに移動するコマンドを入力してください。",
     "choices": [], "answer": "cd ~",
     "explanation": "cd ~ または cd だけでホームディレクトリに移動できます。"},
    {"id": "file_04", "category": "file", "difficulty": 1, "type": "choice",
     "question": "新しいディレクトリ「mydir」を作成するコマンドは？",
     "choices": ["mkdir mydir", "touch mydir", "create mydir", "new mydir"], "answer": "mkdir mydir",
     "explanation": "mkdir (make directory) で新しいディレクトリを作成します。"},
    {"id": "file_05", "category": "file", "difficulty": 1, "type": "choice",
     "question": "空のファイル「note.txt」を新規作成するコマンドは？",
     "choices": ["touch note.txt", "new note.txt", "create note.txt", "make note.txt"], "answer": "touch note.txt",
     "explanation": "touch は空ファイルを作成、または既存ファイルのタイムスタンプを更新します。"},
    {"id": "file_06", "category": "file", "difficulty": 2, "type": "choice",
     "question": "file1.txt を file2.txt にコピーするコマンドは？",
     "choices": ["cp file1.txt file2.txt", "mv file1.txt file2.txt", "ln file1.txt file2.txt", "cat file1.txt > file2.txt"],
     "answer": "cp file1.txt file2.txt",
     "explanation": "cp (copy) でファイルをコピーします。mv は移動（名前変更）になります。"},
    {"id": "file_07", "category": "file", "difficulty": 2, "type": "fill",
     "question": "old.txt を new.txt にリネームするコマンドを入力してください。",
     "choices": [], "answer": "mv old.txt new.txt",
     "explanation": "mv (move) は移動だけでなく、同じディレクトリ内での名前変更にも使います。"},
    {"id": "file_08", "category": "file", "difficulty": 2, "type": "choice",
     "question": "ファイルを削除するコマンドはどれ？",
     "choices": ["rm", "del", "remove", "erase"], "answer": "rm",
     "explanation": "rm (remove) でファイルを削除します。削除したファイルはゴミ箱に入らないので注意！"},
    {"id": "file_09", "category": "file", "difficulty": 2, "type": "choice",
     "question": "ls コマンドで隠しファイルも含めて一覧表示するオプションは？",
     "choices": ["-a", "-l", "-h", "-r"], "answer": "-a",
     "explanation": "ls -a で . から始まる隠しファイルも表示されます。"},
    {"id": "file_10", "category": "file", "difficulty": 3, "type": "fill",
     "question": "ディレクトリ「docs」を中身ごと削除するコマンドを入力してください。",
     "choices": [], "answer": "rm -r docs",
     "explanation": "rm -r (recursive) でディレクトリを再帰的に削除します。-rf は確認なしで削除するので特に注意。"},
    {"id": "file_11", "category": "file", "difficulty": 3, "type": "choice",
     "question": "カレントディレクトリ以下のすべての .log ファイルを検索するコマンドは？",
     "choices": ["find . -name '*.log'", "ls -r *.log", "grep .log .", "search *.log"],
     "answer": "find . -name '*.log'",
     "explanation": "find コマンドで再帰的にファイルを検索できます。-name でファイル名のパターンを指定します。"},
    {"id": "file_12", "category": "file", "difficulty": 2, "type": "choice",
     "question": "ファイルのパーミッション（権限）を変更するコマンドは？",
     "choices": ["chmod", "chown", "chgrp", "sudo"], "answer": "chmod",
     "explanation": "chmod (change mode) でファイルの読み書き実行権限を変更します。"},
    {"id": "file_13", "category": "file", "difficulty": 2, "type": "choice",
     "question": "target.txt へのシンボリックリンク link.txt を作成するコマンドは？",
     "choices": ["ln -s target.txt link.txt", "ln target.txt link.txt", "link -s target.txt link.txt", "mklink target.txt link.txt"],
     "answer": "ln -s target.txt link.txt",
     "explanation": "ln -s でシンボリックリンクを作成します。ハードリンクは ln（-s なし）です。"},
    {"id": "file_14", "category": "file", "difficulty": 1, "type": "choice",
     "question": "script.sh に実行権限を付与するコマンドは？",
     "choices": ["chmod +x script.sh", "chmod -x script.sh", "exec script.sh", "run script.sh"],
     "answer": "chmod +x script.sh",
     "explanation": "chmod +x で実行権限を追加します。"},
    {"id": "file_15", "category": "file", "difficulty": 2, "type": "fill",
     "question": "file.txt のパーミッションを 644（オーナーのみ読み書き、その他読み取りのみ）に設定するコマンドを入力してください。",
     "choices": [], "answer": "chmod 644 file.txt",
     "explanation": "8進数表記: 4=read, 2=write, 1=execute。644 = rw-r--r-- です。"},
    {"id": "file_16", "category": "file", "difficulty": 2, "type": "fill",
     "question": "file.txt のオーナーを alice に変更するコマンドを入力してください。",
     "choices": [], "answer": "chown alice file.txt",
     "explanation": "chown (change owner) でファイルの所有者を変更します。"},
    {"id": "file_17", "category": "file", "difficulty": 2, "type": "choice",
     "question": "ディレクトリ project/ を tar.gz 形式で圧縮するコマンドは？",
     "choices": ["tar -czf project.tar.gz project/", "tar -xzf project.tar.gz", "gzip -r project/", "zip project.tar.gz project/"],
     "answer": "tar -czf project.tar.gz project/",
     "explanation": "tar: c=create, z=gzip圧縮, f=ファイル名指定。展開は -x（extract）を使います。"},
    {"id": "file_18", "category": "file", "difficulty": 2, "type": "fill",
     "question": "backup.tar.gz を現在のディレクトリに展開するコマンドを入力してください。",
     "choices": [], "answer": "tar -xzf backup.tar.gz",
     "explanation": "tar -xzf: x=展開, z=gzip解凍, f=ファイル名。"},
    {"id": "file_19", "category": "file", "difficulty": 1, "type": "choice",
     "question": "file.txt を gzip 圧縮するコマンドはどれ？",
     "choices": ["gzip file.txt", "compress file.txt", "pack file.txt", "zip file.txt"], "answer": "gzip file.txt",
     "explanation": "gzip で圧縮すると file.txt.gz が作成され、元のファイルは削除されます。"},
    {"id": "file_20", "category": "file", "difficulty": 2, "type": "choice",
     "question": "2つのファイルの差分を表示するコマンドは？",
     "choices": ["diff file1.txt file2.txt", "cmp file1.txt file2.txt", "comp file1.txt file2.txt", "compare file1.txt file2.txt"],
     "answer": "diff file1.txt file2.txt",
     "explanation": "diff は2ファイルの差分を表示します。diff -u で unified 形式になります。"},
    {"id": "file_21", "category": "file", "difficulty": 2, "type": "choice",
     "question": "カレントディレクトリ全体のディスク使用量を人間が読みやすい形式で表示するコマンドは？",
     "choices": ["du -sh .", "df -h .", "ls -sh", "stat ."], "answer": "du -sh .",
     "explanation": "du (disk usage): -s は合計のみ, -h は人間が読みやすい形式。"},
    {"id": "file_22", "category": "file", "difficulty": 1, "type": "choice",
     "question": "マウントされたファイルシステムの空き容量を確認するコマンドは？",
     "choices": ["df -h", "du -h", "free -h", "lsblk"], "answer": "df -h",
     "explanation": "df (disk free) でファイルシステムの容量・使用量・空き容量を表示します。"},
    {"id": "file_23", "category": "file", "difficulty": 3, "type": "fill",
     "question": "ローカルの src/ を user@server:/backup/ に差分同期するコマンドを入力してください（rsync使用）。",
     "choices": [], "answer": "rsync -av src/ user@server:/backup/",
     "explanation": "rsync -av: a=アーカイブモード, v=詳細表示。差分のみ転送するため高速です。"},
    {"id": "file_24", "category": "file", "difficulty": 2, "type": "choice",
     "question": "ファイルの種類（テキスト・バイナリ・スクリプトなど）を判定するコマンドは？",
     "choices": ["file script.sh", "type script.sh", "stat script.sh", "info script.sh"], "answer": "file script.sh",
     "explanation": "file コマンドはファイルの種類を判定します。"},
    {"id": "file_25", "category": "file", "difficulty": 3, "type": "choice",
     "question": "ファイルの iノード番号・アクセス/変更/更新時刻を詳しく確認するコマンドは？",
     "choices": ["stat file.txt", "ls -li file.txt", "info file.txt", "meta file.txt"], "answer": "stat file.txt",
     "explanation": "stat はファイルのメタデータを詳しく表示します。"},
    {"id": "file_26", "category": "file", "difficulty": 2, "type": "choice",
     "question": "tar.gz ファイルの中身を展開せずに一覧表示するコマンドは？",
     "choices": ["tar -tzf archive.tar.gz", "tar -czf archive.tar.gz", "tar -xzf archive.tar.gz", "tar -lzf archive.tar.gz"],
     "answer": "tar -tzf archive.tar.gz",
     "explanation": "tar -t (list) でアーカイブの内容を一覧できます。"},
    {"id": "file_27", "category": "file", "difficulty": 3, "type": "choice",
     "question": "シンボリックリンクのリンク先パスを表示するコマンドは？",
     "choices": ["readlink linkname", "ls -l linkname", "stat linkname", "file linkname"], "answer": "readlink linkname",
     "explanation": "readlink はシンボリックリンクが指す先のパスを表示します。"},

    # ══════════════════════════════════════════════════════════
    # 📝 テキスト処理
    # ══════════════════════════════════════════════════════════
    {"id": "text_01", "category": "text", "difficulty": 1, "type": "choice",
     "question": "ファイルの内容を表示するコマンドは？",
     "choices": ["cat", "show", "print", "read"], "answer": "cat",
     "explanation": "cat (concatenate) でファイルの内容を標準出力に表示します。"},
    {"id": "text_02", "category": "text", "difficulty": 1, "type": "choice",
     "question": "ファイルの最初の10行を表示するコマンドは？",
     "choices": ["head", "tail", "top", "first"], "answer": "head",
     "explanation": "head はデフォルトで先頭10行を表示します。head -n 20 で行数を指定できます。"},
    {"id": "text_03", "category": "text", "difficulty": 1, "type": "choice",
     "question": "ファイルの最後の10行を表示するコマンドは？",
     "choices": ["tail", "head", "last", "end"], "answer": "tail",
     "explanation": "tail はデフォルトで末尾10行を表示します。tail -f はリアルタイムでログを追跡できます。"},
    {"id": "text_04", "category": "text", "difficulty": 1, "type": "fill",
     "question": "file.txt から「error」という文字列を含む行を検索するコマンドを入力してください。",
     "choices": [], "answer": "grep error file.txt",
     "explanation": "grep で指定パターンを含む行を検索します。-i で大文字小文字を無視できます。"},
    {"id": "text_05", "category": "text", "difficulty": 2, "type": "choice",
     "question": "テキストファイルを1画面ずつスクロールして表示するコマンドはどれ？",
     "choices": ["less", "cat", "more", "view"], "answer": "less",
     "explanation": "less はページャーです。more より高機能で上下スクロールが可能です。"},
    {"id": "text_06", "category": "text", "difficulty": 2, "type": "choice",
     "question": "ファイルの行数を数えるコマンドはどれ？",
     "choices": ["wc -l", "count -l", "ls -l", "cat -n"], "answer": "wc -l",
     "explanation": "wc (word count) の -l オプションで行数を表示します。"},
    {"id": "text_07", "category": "text", "difficulty": 2, "type": "fill",
     "question": "file.txt 内の「foo」を「bar」に置換して表示するコマンドを入力してください（sed使用）。",
     "choices": [], "answer": "sed 's/foo/bar/g' file.txt",
     "explanation": "sed の s/old/new/g で置換します。g フラグで行内の全一致を置換します。"},
    {"id": "text_08", "category": "text", "difficulty": 2, "type": "choice",
     "question": "テキストをアルファベット順に並べ替えるコマンドは？",
     "choices": ["sort", "order", "arrange", "awk"], "answer": "sort",
     "explanation": "sort コマンドで行を並べ替えます。sort -r で逆順、sort -n で数値順になります。"},
    {"id": "text_09", "category": "text", "difficulty": 2, "type": "choice",
     "question": "連続する重複した行を取り除くコマンドは？",
     "choices": ["uniq", "sort -u", "unique", "dedup"], "answer": "uniq",
     "explanation": "uniq は連続する重複行を取り除きます。sort | uniq の組み合わせでよく使われます。"},
    {"id": "text_10", "category": "text", "difficulty": 2, "type": "choice",
     "question": "CSV の2列目だけを取り出すコマンドはどれ？",
     "choices": ["cut -d',' -f2", "cat -f2", "awk -f2", "grep -f2"], "answer": "cut -d',' -f2",
     "explanation": "cut -d',' -f2 はカンマ区切りの2フィールド目を取り出します。"},
    {"id": "text_11", "category": "text", "difficulty": 3, "type": "fill",
     "question": "log.txt から「ERROR」を含む行を数えるコマンドを入力してください（grep + wc 使用）。",
     "choices": [], "answer": "grep ERROR log.txt | wc -l",
     "explanation": "| (パイプ) で複数コマンドをつなぎ、前のコマンドの出力を次の入力として渡します。"},
    {"id": "text_12", "category": "text", "difficulty": 2, "type": "choice",
     "question": "data.csv のスペース区切りで各行の2番目のフィールドを表示する awk コマンドは？",
     "choices": ["awk '{print $2}' data.csv", "awk '{print $1}' data.csv", "awk -f2 data.csv", "awk 'NR==2' data.csv"],
     "answer": "awk '{print $2}' data.csv",
     "explanation": "awk で $1, $2, $3... がフィールドを表します。$0 は行全体です。"},
    {"id": "text_13", "category": "text", "difficulty": 2, "type": "fill",
     "question": "data.csv のコロン区切りで1フィールド目を表示する awk コマンドを入力してください。",
     "choices": [], "answer": "awk -F':' '{print $1}' data.csv",
     "explanation": "awk の -F オプションでフィールド区切り文字を指定します。"},
    {"id": "text_14", "category": "text", "difficulty": 3, "type": "choice",
     "question": "awk でヘッダー行をスキップして2行目以降のデータだけを表示するコマンドは？",
     "choices": ["awk 'NR>1' file.csv", "awk 'NR==1' file.csv", "awk 'skip 1' file.csv", "awk '{skip first}' file.csv"],
     "answer": "awk 'NR>1' file.csv",
     "explanation": "NR は現在の行番号です。NR>1 で2行目以降だけを処理します。"},
    {"id": "text_15", "category": "text", "difficulty": 2, "type": "choice",
     "question": "小文字を大文字に変換するコマンドはどれ？",
     "choices": ["echo 'hello' | tr 'a-z' 'A-Z'", "echo 'hello' | upper", "echo 'hello' | awk '{toupper}'", "echo 'hello' | sed upper"],
     "answer": "echo 'hello' | tr 'a-z' 'A-Z'",
     "explanation": "tr (translate) は文字の置換や削除を行います。"},
    {"id": "text_16", "category": "text", "difficulty": 2, "type": "fill",
     "question": "テキストから改行文字（\\n）を削除するコマンドを入力してください（tr 使用）。",
     "choices": [], "answer": "tr -d '\\n'",
     "explanation": "tr -d で指定した文字を削除します。"},
    {"id": "text_17", "category": "text", "difficulty": 2, "type": "choice",
     "question": "find の出力を xargs に渡して grep で一括検索するコマンドはどれ？",
     "choices": ["find . -name '*.txt' | xargs grep 'word'", "find . -name '*.txt' | grep 'word'", "find . -name '*.txt' -grep 'word'", "xargs find . -name '*.txt' grep 'word'"],
     "answer": "find . -name '*.txt' | xargs grep 'word'",
     "explanation": "xargs は標準入力を受け取り、それを引数として別のコマンドを実行します。"},
    {"id": "text_18", "category": "text", "difficulty": 2, "type": "choice",
     "question": "コマンドの出力をファイルに保存しながら画面にも表示するコマンドは？",
     "choices": ["tee", "cat", "pipe", "dual"], "answer": "tee",
     "explanation": "tee は標準入力を標準出力とファイルの両方に書き出します。"},
    {"id": "text_19", "category": "text", "difficulty": 3, "type": "fill",
     "question": "ls の結果を output.txt に保存しながら画面にも表示するコマンドを入力してください（tee 使用）。",
     "choices": [], "answer": "ls | tee output.txt",
     "explanation": "ls | tee output.txt で ls の出力を画面表示と同時に output.txt に保存します。"},
    {"id": "text_20", "category": "text", "difficulty": 1, "type": "choice",
     "question": "less コマンドで前のページに戻るキーは？",
     "choices": ["b", "p", "u", "↑"], "answer": "b",
     "explanation": "less では b で前ページ、スペースで次ページ、/ で検索、q で終了します。"},
    {"id": "text_21", "category": "text", "difficulty": 3, "type": "choice",
     "question": "awk でファイルの各行の合計値を計算するコマンドは？（例: 各行が数値）",
     "choices": ["awk '{sum+=$1} END{print sum}' file.txt", "awk '{sum=$1} print sum' file.txt", "awk 'sum($1)' file.txt", "awk '{total $1}' file.txt"],
     "answer": "awk '{sum+=$1} END{print sum}' file.txt",
     "explanation": "awk の END ブロックは全行処理後に実行されます。"},
    {"id": "text_22", "category": "text", "difficulty": 3, "type": "choice",
     "question": "2つのファイルを行ごとに並べて結合するコマンドは？",
     "choices": ["paste file1.txt file2.txt", "cat file1.txt file2.txt", "join file1.txt file2.txt", "merge file1.txt file2.txt"],
     "answer": "paste file1.txt file2.txt",
     "explanation": "paste はファイルを列方向（横）に結合します。cat は行方向（縦）に結合します。"},
    {"id": "text_23", "category": "text", "difficulty": 2, "type": "choice",
     "question": "テキストに行番号を付けて表示するコマンドは？",
     "choices": ["nl file.txt", "cat -n file.txt", "num file.txt", "line file.txt"], "answer": "nl file.txt",
     "explanation": "nl (number lines) で行番号を付けて表示します。"},
    {"id": "text_24", "category": "text", "difficulty": 3, "type": "fill",
     "question": "log.txt の中で「ERROR」が含まれる行を抽出して出現回数の多い順に並べるコマンドを入力してください。",
     "choices": [], "answer": "grep ERROR log.txt | sort | uniq -c | sort -rn",
     "explanation": "grep→sort→uniq -c（出現回数付き）→sort -rn（数値逆順）のパイプチェーンは頻度分析の定番パターンです。"},

    # ══════════════════════════════════════════════════════════
    # ⚙️  プロセス管理
    # ══════════════════════════════════════════════════════════
    {"id": "proc_01", "category": "process", "difficulty": 1, "type": "choice",
     "question": "現在実行中のプロセスを一覧表示するコマンドは？",
     "choices": ["ps", "ls", "top", "jobs"], "answer": "ps",
     "explanation": "ps (process status) でプロセス一覧を表示します。ps aux でより詳細な情報が見えます。"},
    {"id": "proc_02", "category": "process", "difficulty": 1, "type": "choice",
     "question": "CPU・メモリ使用率をリアルタイムで監視するコマンドは？",
     "choices": ["top", "ps", "htop", "watch"], "answer": "top",
     "explanation": "top はプロセスの状態をリアルタイムで表示します。q で終了します。"},
    {"id": "proc_03", "category": "process", "difficulty": 1, "type": "fill",
     "question": "PID 1234 のプロセスを終了させるコマンドを入力してください。",
     "choices": [], "answer": "kill 1234",
     "explanation": "kill にPIDを渡してプロセスにシグナルを送ります。デフォルトは SIGTERM です。"},
    {"id": "proc_04", "category": "process", "difficulty": 2, "type": "choice",
     "question": "「python」という名前のプロセスを強制終了するコマンドは？",
     "choices": ["killall python", "kill python", "stop python", "end python"], "answer": "killall python",
     "explanation": "killall はプロセス名でシグナルを送ります。-9 オプションで強制終了（SIGKILL）できます。"},
    {"id": "proc_05", "category": "process", "difficulty": 2, "type": "choice",
     "question": "コマンドをバックグラウンドで実行するには？",
     "choices": ["コマンドの末尾に & を付ける", "コマンドの先頭に bg を付ける", "Ctrl+B を押す", "コマンドの末尾に # を付ける"],
     "answer": "コマンドの末尾に & を付ける",
     "explanation": "command & でバックグラウンド実行します。fg コマンドでフォアグラウンドに戻せます。"},
    {"id": "proc_06", "category": "process", "difficulty": 2, "type": "choice",
     "question": "フォアグラウンドのプロセスを一時停止するキーは？",
     "choices": ["Ctrl+Z", "Ctrl+C", "Ctrl+S", "Ctrl+D"], "answer": "Ctrl+Z",
     "explanation": "Ctrl+Z でプロセスを一時停止（SIGTSTP）します。bg コマンドでバックグラウンド再開できます。"},
    {"id": "proc_07", "category": "process", "difficulty": 2, "type": "choice",
     "question": "バックグラウンドジョブの一覧を表示するコマンドは？",
     "choices": ["jobs", "ps", "bg", "top"], "answer": "jobs",
     "explanation": "jobs で現在のシェルのバックグラウンドジョブが表示されます。"},
    {"id": "proc_08", "category": "process", "difficulty": 3, "type": "fill",
     "question": "「nginx」という名前のプロセスのPIDを確認するコマンドを入力してください（pgrep使用）。",
     "choices": [], "answer": "pgrep nginx",
     "explanation": "pgrep はプロセス名でPIDを検索します。"},
    {"id": "proc_09", "category": "process", "difficulty": 3, "type": "choice",
     "question": "ターミナルを閉じてもプロセスを継続させるコマンドはどれ？",
     "choices": ["nohup", "disown", "bg", "screen"], "answer": "nohup",
     "explanation": "nohup コマンドを先頭に付けると、HUPシグナルを無視してプロセスが継続します。"},
    {"id": "proc_10", "category": "process", "difficulty": 2, "type": "choice",
     "question": "kill -9 が使う強制終了シグナルの名前は？",
     "choices": ["SIGKILL", "SIGTERM", "SIGHUP", "SIGSTOP"], "answer": "SIGKILL",
     "explanation": "SIGKILL はプロセスが無視できない強制終了シグナルです。"},
    {"id": "proc_11", "category": "process", "difficulty": 2, "type": "choice",
     "question": "定期実行タスクを設定するコマンドは？",
     "choices": ["crontab -e", "at -e", "schedule -e", "timer -e"], "answer": "crontab -e",
     "explanation": "crontab -e でcrontabをエディタで編集します。"},
    {"id": "proc_12", "category": "process", "difficulty": 3, "type": "choice",
     "question": "毎日午前3時にスクリプトを実行するcron書式はどれ？",
     "choices": ["0 3 * * * /path/script.sh", "3 0 * * * /path/script.sh", "* * 3 * * /path/script.sh", "0 * 3 * * /path/script.sh"],
     "answer": "0 3 * * * /path/script.sh",
     "explanation": "cron の書式: 分 時 日 月 曜日 コマンド。0 3 * * * は毎日3時0分に実行します。"},
    {"id": "proc_13", "category": "process", "difficulty": 2, "type": "choice",
     "question": "プロセスの優先度（nice値）を下げて（低優先度で）起動するコマンドは？",
     "choices": ["nice -n 10 command", "nice +10 command", "renice 10 command", "low command"],
     "answer": "nice -n 10 command",
     "explanation": "nice -n 10 で nice値+10（低優先度）でコマンドを起動します。"},
    {"id": "proc_14", "category": "process", "difficulty": 3, "type": "fill",
     "question": "PID 5678 のプロセスの優先度を nice値 5 に変更するコマンドを入力してください。",
     "choices": [], "answer": "renice 5 5678",
     "explanation": "renice は実行中プロセスのnice値を変更します。"},
    {"id": "proc_15", "category": "process", "difficulty": 2, "type": "choice",
     "question": "特定のファイルを開いているプロセスを確認するコマンドは？",
     "choices": ["lsof /path/to/file", "ps /path/to/file", "fuser /path/to/file", "open /path/to/file"],
     "answer": "lsof /path/to/file",
     "explanation": "lsof (list open files) でファイルを開いているプロセスを確認できます。"},
    {"id": "proc_16", "category": "process", "difficulty": 2, "type": "choice",
     "question": "1秒ごとに df -h を実行し続けるコマンドは？",
     "choices": ["watch -n 1 df -h", "repeat 1 df -h", "loop -n 1 df -h", "timer 1 df -h"],
     "answer": "watch -n 1 df -h",
     "explanation": "watch -n 秒数 コマンド でコマンドを定期実行して結果を更新表示します。"},
    {"id": "proc_17", "category": "process", "difficulty": 2, "type": "choice",
     "question": "コマンドを5秒以内に完了しない場合に強制終了するコマンドは？",
     "choices": ["timeout 5 command", "limit 5 command", "expire 5 command", "kill -t 5 command"],
     "answer": "timeout 5 command",
     "explanation": "timeout 秒数 コマンド で実行時間を制限できます。"},
    {"id": "proc_18", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Linux でサービスの起動・停止・状態確認に使うコマンドは？",
     "choices": ["systemctl", "service", "init", "daemon"], "answer": "systemctl",
     "explanation": "systemctl start/stop/status サービス名 でサービスを管理します。"},
    {"id": "proc_19", "category": "process", "difficulty": 3, "type": "choice",
     "question": "80番ポートを使用しているプロセスを確認するコマンドは？",
     "choices": ["lsof -i :80", "ps -p 80", "netstat -p 80", "port -l 80"], "answer": "lsof -i :80",
     "explanation": "lsof -i :ポート番号 でそのポートを使っているプロセスを確認できます。"},
    {"id": "proc_20", "category": "process", "difficulty": 3, "type": "fill",
     "question": "10分後に echo 'done' を実行するコマンドを入力してください（at 使用）。",
     "choices": [], "answer": "echo 'echo done' | at now + 10 minutes",
     "explanation": "at は指定時刻にコマンドを一度だけ実行します。"},

    # ══════════════════════════════════════════════════════════
    # 🌐 ネットワーク
    # ══════════════════════════════════════════════════════════
    {"id": "net_01", "category": "network", "difficulty": 1, "type": "choice",
     "question": "ホストへの疎通確認をするコマンドは？",
     "choices": ["ping", "curl", "ssh", "traceroute"], "answer": "ping",
     "explanation": "ping はICMPエコー要求を送り、ホストへの到達性と応答時間を確認します。"},
    {"id": "net_02", "category": "network", "difficulty": 1, "type": "fill",
     "question": "example.com にSSH接続するコマンドを入力してください（ユーザー名: user）。",
     "choices": [], "answer": "ssh user@example.com",
     "explanation": "ssh ユーザー名@ホスト名 で安全なリモートログインができます。"},
    {"id": "net_03", "category": "network", "difficulty": 1, "type": "choice",
     "question": "URLのHTTPレスポンスを取得するコマンドは？",
     "choices": ["curl", "wget", "fetch", "get"], "answer": "curl",
     "explanation": "curl はURLへのリクエストを送り、レスポンスを表示します。"},
    {"id": "net_04", "category": "network", "difficulty": 1, "type": "choice",
     "question": "自分のマシンのネットワークインターフェース情報を確認するコマンドは？",
     "choices": ["ifconfig", "ipconfig", "myip", "netinfo"], "answer": "ifconfig",
     "explanation": "ifconfig でネットワークインターフェースの設定を表示します。"},
    {"id": "net_05", "category": "network", "difficulty": 2, "type": "choice",
     "question": "ドメイン名からIPアドレスを調べるコマンドは？",
     "choices": ["nslookup", "lookup", "resolv", "host"], "answer": "nslookup",
     "explanation": "nslookup でDNS問い合わせを行います。dig コマンドもより詳細なDNS情報を確認できます。"},
    {"id": "net_06", "category": "network", "difficulty": 2, "type": "fill",
     "question": "example.com の80番ポートが開いているか確認するコマンドを入力してください（nc使用）。",
     "choices": [], "answer": "nc -zv example.com 80",
     "explanation": "nc (netcat) の -z でスキャンモード、-v で詳細表示。"},
    {"id": "net_07", "category": "network", "difficulty": 2, "type": "choice",
     "question": "パケットがどのルーターを経由しているか確認するコマンドは？",
     "choices": ["traceroute", "ping", "route", "netstat"], "answer": "traceroute",
     "explanation": "traceroute で送信元から宛先までの経路（ホップ）を確認できます。"},
    {"id": "net_08", "category": "network", "difficulty": 2, "type": "choice",
     "question": "URLからファイルをダウンロードして保存するコマンドはどれ？",
     "choices": ["wget https://example.com/file", "curl https://example.com/file", "fetch https://example.com/file", "download https://example.com/file"],
     "answer": "wget https://example.com/file",
     "explanation": "wget はURLからファイルをダウンロードして保存します。"},
    {"id": "net_09", "category": "network", "difficulty": 3, "type": "choice",
     "question": "使用中のTCPポートをプロセスと一覧表示するコマンドは？",
     "choices": ["lsof -i -P -n", "netstat -an", "ss -tlnp", "ps -net"], "answer": "lsof -i -P -n",
     "explanation": "lsof -i で開いているネットワーク接続を表示します。"},
    {"id": "net_10", "category": "network", "difficulty": 3, "type": "fill",
     "question": "ローカルの8080番ポートをリモートサーバーの80番ポートにSSHトンネリングするコマンドを入力してください（サーバー: srv.example.com、ユーザー: user）。",
     "choices": [], "answer": "ssh -L 8080:localhost:80 user@srv.example.com",
     "explanation": "ssh -L ローカルポート:転送先:転送先ポート でポートフォワーディングが設定できます。"},
    {"id": "net_11", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Linux でネットワークインターフェースのIPアドレスを確認する現代的なコマンドは？",
     "choices": ["ip addr show", "ifconfig", "netstat -i", "route -n"], "answer": "ip addr show",
     "explanation": "ip コマンド（iproute2）は ifconfig の後継です。"},
    {"id": "net_12", "category": "network", "difficulty": 2, "type": "fill",
     "question": "デフォルトゲートウェイを含むルーティングテーブルを確認するコマンドを入力してください（ip コマンド使用）。",
     "choices": [], "answer": "ip route show",
     "explanation": "ip route show でルーティングテーブルを表示します。"},
    {"id": "net_13", "category": "network", "difficulty": 2, "type": "choice",
     "question": "現在のTCP/UDP接続状態を表示するコマンドはどれ？",
     "choices": ["netstat -an", "ps -net", "lsof -net", "conn -a"], "answer": "netstat -an",
     "explanation": "netstat -an で全ての接続とリスニングポートを表示します。"},
    {"id": "net_14", "category": "network", "difficulty": 3, "type": "choice",
     "question": "ss コマンドで LISTEN 状態の TCP ポートをプロセス名付きで表示するコマンドは？",
     "choices": ["ss -tlnp", "ss -an", "ss -tcp", "ss -listen"], "answer": "ss -tlnp",
     "explanation": "ss (socket statistics) は netstat の後継です。-t=TCP, -l=LISTEN, -n=数値表示, -p=プロセス名付き。"},
    {"id": "net_15", "category": "network", "difficulty": 2, "type": "choice",
     "question": "より詳細な DNS 情報を調査するコマンドはどれ？",
     "choices": ["dig", "nslookup", "host", "resolve"], "answer": "dig",
     "explanation": "dig (domain information groper) は DNS の詳細情報を確認できます。"},
    {"id": "net_16", "category": "network", "difficulty": 2, "type": "fill",
     "question": "dig コマンドで google.com の A レコードだけを表示するコマンドを入力してください。",
     "choices": [], "answer": "dig +short google.com",
     "explanation": "dig +short はIPアドレスなど結果だけを簡潔に表示します。"},
    {"id": "net_17", "category": "network", "difficulty": 2, "type": "fill",
     "question": "ローカルの file.txt を user@server.com のホームディレクトリにコピーするコマンドを入力してください（scp 使用）。",
     "choices": [], "answer": "scp file.txt user@server.com:~/",
     "explanation": "scp (secure copy) はSSHを使った安全なファイルコピーです。"},
    {"id": "net_18", "category": "network", "difficulty": 1, "type": "choice",
     "question": "自分のマシンのホスト名を確認するコマンドは？",
     "choices": ["hostname", "uname -n", "cat /etc/hostname", "id -h"], "answer": "hostname",
     "explanation": "hostname コマンドでシステムのホスト名を表示します。"},
    {"id": "net_19", "category": "network", "difficulty": 3, "type": "choice",
     "question": "curl を使って HTTP POST リクエストを JSON で送るコマンドはどれ？",
     "choices": [
         "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' URL",
         "curl POST -json '{\"key\":\"val\"}' URL",
         "curl -p '{\"key\":\"val\"}' URL",
         "curl --post-json '{\"key\":\"val\"}' URL",
     ],
     "answer": "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' URL",
     "explanation": "curl -X でHTTPメソッド、-H でヘッダー、-d でリクエストボディを指定します。"},
    {"id": "net_20", "category": "network", "difficulty": 2, "type": "choice",
     "question": "SSH接続で使う鍵ペアを生成するコマンドは？",
     "choices": ["ssh-keygen", "keygen", "ssh -genkey", "openssl genrsa"], "answer": "ssh-keygen",
     "explanation": "ssh-keygen でRSAやEd25519の鍵ペアを生成します。"},

    # ══════════════════════════════════════════════════════════
    # 🐚 シェル・環境
    # ══════════════════════════════════════════════════════════
    {"id": "shell_01", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "ls コマンドのマニュアル（使い方）を表示するコマンドは？",
     "choices": ["man ls", "help ls", "ls --help", "info ls"], "answer": "man ls",
     "explanation": "man (manual) コマンドでマニュアルページを表示します。q で終了、/ で検索できます。"},
    {"id": "shell_02", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "python3 コマンドの実際のパスを確認するコマンドを入力してください。",
     "choices": [], "answer": "which python3",
     "explanation": "which はコマンドの実行ファイルのパスを表示します。"},
    {"id": "shell_03", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "cd がシェル組み込みコマンドかどうかを確認するコマンドは？",
     "choices": ["type cd", "which cd", "whereis cd", "file cd"], "answer": "type cd",
     "explanation": "type はコマンドの種類（シェル組み込み・外部コマンド・エイリアスなど）を表示します。"},
    {"id": "shell_04", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "環境変数 HOME の値を表示するコマンドは？",
     "choices": ["echo $HOME", "print HOME", "env HOME", "show $HOME"], "answer": "echo $HOME",
     "explanation": "$ を付けると変数の値を展開します。"},
    {"id": "shell_05", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "現在のシェルに環境変数 MY_VAR=hello を設定して子プロセスにも引き継ぐコマンドを入力してください。",
     "choices": [], "answer": "export MY_VAR=hello",
     "explanation": "export で変数を環境変数として設定します。"},
    {"id": "shell_06", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "現在の環境変数をすべて表示するコマンドは？",
     "choices": ["env", "set", "printenv", "vars"], "answer": "env",
     "explanation": "env で現在の全環境変数を表示します。"},
    {"id": "shell_07", "category": "shell", "difficulty": 2, "type": "fill",
     "question": "/usr/local/bin を $PATH に追加するコマンドを入力してください。",
     "choices": [], "answer": "export PATH=$PATH:/usr/local/bin",
     "explanation": "$PATH の末尾に追加するには export PATH=$PATH:追加パス と書きます。"},
    {"id": "shell_08", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "~/.bashrc の変更を現在のシェルに即座に反映させるコマンドは？",
     "choices": ["source ~/.bashrc", "exec ~/.bashrc", "run ~/.bashrc", "bash ~/.bashrc"],
     "answer": "source ~/.bashrc",
     "explanation": "source（または .）はファイルを現在のシェルで読み込みます。"},
    {"id": "shell_09", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "ll という名前で ls -la を実行するエイリアスを作成するコマンドを入力してください。",
     "choices": [], "answer": "alias ll='ls -la'",
     "explanation": "alias 名前='コマンド' でエイリアスを作成します。"},
    {"id": "shell_10", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "設定されているエイリアスの一覧を表示するコマンドは？",
     "choices": ["alias", "list alias", "show alias", "env alias"], "answer": "alias",
     "explanation": "引数なしの alias で現在のエイリアス一覧を表示します。"},
    {"id": "shell_11", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "過去に実行したコマンドの履歴を表示するコマンドは？",
     "choices": ["history", "last", "log", "recent"], "answer": "history",
     "explanation": "history で過去に実行したコマンドの一覧と番号が表示されます。"},
    {"id": "shell_12", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "直前に実行したコマンドを再実行するショートカットは？",
     "choices": ["!!", "!-1", "^r", "↑ + Enter"], "answer": "!!",
     "explanation": "!! は直前のコマンドを展開して実行します。sudo !! でも使えます。"},
    {"id": "shell_13", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "直前のコマンドの最後の引数を参照するシェル変数は？",
     "choices": ["$_", "$$", "$!", "$#"], "answer": "$_",
     "explanation": "$_ は直前のコマンドの最後の引数を参照します。"},
    {"id": "shell_14", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "直前のコマンドの終了ステータス（成功=0, 失敗=非0）を確認する変数は？",
     "choices": ["$?", "$!", "$$", "$0"], "answer": "$?",
     "explanation": "$? は直前のコマンドの終了ステータスを保持します。0は成功、1以上はエラーです。"},
    {"id": "shell_15", "category": "shell", "difficulty": 3, "type": "choice",
     "question": "シェルスクリプトの第1引数と第2引数を参照する変数は？",
     "choices": ["$1 と $2", "@1 と @2", "%1 と %2", "#1 と #2"], "answer": "$1 と $2",
     "explanation": "$1, $2, $3... でスクリプトの引数を参照します。$# は引数の数、$@ はすべての引数を表します。"},
    {"id": "shell_16", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "シングルクォート（'）とダブルクォート（\"）の違いは？",
     "choices": [
         "'は変数展開しない、\"は変数展開する",
         "どちらも同じ",
         "'は変数展開する、\"は変数展開しない",
         "'は数値用、\"は文字列用",
     ],
     "answer": "'は変数展開しない、\"は変数展開する",
     "explanation": "シングルクォートは文字をそのまま扱います。ダブルクォートは変数展開します。"},
    {"id": "shell_17", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "カレントディレクトリの .txt ファイルすべてに一致するグロブパターンは？",
     "choices": ["*.txt", "?.txt", "[.txt]", "%.txt"], "answer": "*.txt",
     "explanation": "* は0文字以上の任意の文字列に一致します。"},
    {"id": "shell_18", "category": "shell", "difficulty": 3, "type": "choice",
     "question": "シェルスクリプトでエラー発生時に即座に終了するオプションは？",
     "choices": ["set -e", "set -x", "set -u", "set -o"], "answer": "set -e",
     "explanation": "set -e でエラー発生時にスクリプトを即座に終了します。"},

    # ══════════════════════════════════════════════════════════
    # 💻 システム情報
    # ══════════════════════════════════════════════════════════
    {"id": "sys_01", "category": "system", "difficulty": 1, "type": "choice",
     "question": "OS名・カーネルバージョン・ハードウェア情報を一括表示するコマンドは？",
     "choices": ["uname -a", "uname -r", "uname -s", "sysinfo"], "answer": "uname -a",
     "explanation": "uname -a (all) でシステム名・ノード名・カーネルバージョン・ハードウェアなどをすべて表示します。"},
    {"id": "sys_02", "category": "system", "difficulty": 1, "type": "fill",
     "question": "カーネルのバージョンのみを表示するコマンドを入力してください。",
     "choices": [], "answer": "uname -r",
     "explanation": "uname -r (release) でカーネルバージョンのみを表示します。"},
    {"id": "sys_03", "category": "system", "difficulty": 1, "type": "choice",
     "question": "システムの起動時間と負荷平均を確認するコマンドは？",
     "choices": ["uptime", "top", "ps", "sysctl"], "answer": "uptime",
     "explanation": "uptime で現在時刻・起動からの経過時間・ログインユーザー数・ロードアベレージを表示します。"},
    {"id": "sys_04", "category": "system", "difficulty": 1, "type": "choice",
     "question": "現在の日時を表示するコマンドは？",
     "choices": ["date", "time", "clock", "now"], "answer": "date",
     "explanation": "date で現在の日時を表示します。date +\"%Y-%m-%d %H:%M\" でフォーマット指定もできます。"},
    {"id": "sys_05", "category": "system", "difficulty": 2, "type": "fill",
     "question": "date コマンドで「2026-06-11」形式（年-月-日）で表示するコマンドを入力してください。",
     "choices": [], "answer": "date +%Y-%m-%d",
     "explanation": "date +フォーマット で出力形式を指定します。%Y=4桁年, %m=月, %d=日です。"},
    {"id": "sys_06", "category": "system", "difficulty": 1, "type": "choice",
     "question": "現在ログインしているユーザーの一覧を確認するコマンドは？",
     "choices": ["who", "users", "id", "last"], "answer": "who",
     "explanation": "who でログインしているユーザー・端末・ログイン日時を表示します。"},
    {"id": "sys_07", "category": "system", "difficulty": 1, "type": "choice",
     "question": "現在のユーザーのUID・GIDとグループを確認するコマンドは？",
     "choices": ["id", "who", "whoami", "groups"], "answer": "id",
     "explanation": "id で UID（ユーザーID）・GID（グループID）・所属グループを表示します。"},
    {"id": "sys_08", "category": "system", "difficulty": 2, "type": "choice",
     "question": "ログインしているユーザーが実行中のコマンドを含む詳細を表示するコマンドは？",
     "choices": ["w", "who", "ps", "top"], "answer": "w",
     "explanation": "w コマンドは who より詳細で、各ユーザーが何のコマンドを実行しているかも表示します。"},
    {"id": "sys_09", "category": "system", "difficulty": 2, "type": "choice",
     "question": "各ファイルシステムのディスク容量を人間が読みやすい形式で確認するコマンドは？",
     "choices": ["df -h", "du -h", "lsblk", "fdisk -l"], "answer": "df -h",
     "explanation": "df -h で全ファイルシステムの合計・使用済み・空き容量を表示します。"},
    {"id": "sys_10", "category": "system", "difficulty": 2, "type": "fill",
     "question": "カレントディレクトリ内の各ファイル・ディレクトリのサイズを一覧表示するコマンドを入力してください（du使用）。",
     "choices": [], "answer": "du -sh *",
     "explanation": "du -sh * でカレントディレクトリ内の各アイテムのサイズを表示します。"},
    {"id": "sys_11", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Linux でメモリの使用状況を確認するコマンドは？",
     "choices": ["free -h", "mem -h", "vmstat -h", "top -m"], "answer": "free -h",
     "explanation": "free -h で合計・使用済み・空きメモリを表示します。macOS では vm_stat または top を使います。"},
    {"id": "sys_12", "category": "system", "difficulty": 3, "type": "choice",
     "question": "カーネルのリングバッファ（起動ログ・デバイスエラーなど）を確認するコマンドは？",
     "choices": ["dmesg", "syslog", "journalctl", "klog"], "answer": "dmesg",
     "explanation": "dmesg でカーネルメッセージを表示します。"},
    {"id": "sys_13", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Linux でCPU情報（コア数・モデル名など）を確認するファイルは？",
     "choices": ["/proc/cpuinfo", "/sys/cpu/info", "/dev/cpu", "/etc/cpuinfo"], "answer": "/proc/cpuinfo",
     "explanation": "/proc/cpuinfo でCPUの詳細情報を確認できます。"},
    {"id": "sys_14", "category": "system", "difficulty": 3, "type": "choice",
     "question": "システムのカーネルパラメータを確認・変更するコマンドは？",
     "choices": ["sysctl", "syscfg", "kparam", "modprobe"], "answer": "sysctl",
     "explanation": "sysctl -a で全カーネルパラメータを表示します。"},
    {"id": "sys_15", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Linux の OS ディストリビューション名とバージョンを確認するファイルは？",
     "choices": ["/etc/os-release", "/etc/version", "/proc/version", "/etc/distro"], "answer": "/etc/os-release",
     "explanation": "cat /etc/os-release で Ubuntu/CentOS/Debian などのディストリビューション名とバージョンを確認できます。"},
]
