"""Question database (English)"""

from typing import TypedDict


class Question(TypedDict):
    id: str
    category: str
    difficulty: int
    type: str
    question: str
    choices: list[str]
    answer: str
    explanation: str


QUESTIONS: list[Question] = [

    # ══════════════════════════════════════════════════════════
    # 📁 File Operations
    # ══════════════════════════════════════════════════════════
    {"id": "file_01", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command lists the files in the current directory?",
     "choices": ["ls", "cd", "pwd", "cat"], "answer": "ls",
     "explanation": "ls (list) displays the contents of a directory."},
    {"id": "file_02", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command shows the path of your current directory?",
     "choices": ["pwd", "ls", "cd", "echo"], "answer": "pwd",
     "explanation": "pwd (print working directory) displays the full path of where you are."},
    {"id": "file_03", "category": "file", "difficulty": 1, "type": "fill",
     "question": "Type the command to go to your home directory.",
     "choices": [], "answer": "cd ~",
     "explanation": "cd ~ (or just cd) takes you to your home directory."},
    {"id": "file_04", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command creates a new directory called 'mydir'?",
     "choices": ["mkdir mydir", "touch mydir", "create mydir", "new mydir"], "answer": "mkdir mydir",
     "explanation": "mkdir (make directory) creates a new directory."},
    {"id": "file_05", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command creates an empty file called 'note.txt'?",
     "choices": ["touch note.txt", "new note.txt", "create note.txt", "make note.txt"], "answer": "touch note.txt",
     "explanation": "touch creates an empty file, or updates the timestamp of an existing one."},
    {"id": "file_06", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command copies file1.txt to file2.txt?",
     "choices": ["cp file1.txt file2.txt", "mv file1.txt file2.txt", "ln file1.txt file2.txt", "cat file1.txt > file2.txt"],
     "answer": "cp file1.txt file2.txt",
     "explanation": "cp (copy) copies a file. mv moves (or renames) it."},
    {"id": "file_07", "category": "file", "difficulty": 2, "type": "fill",
     "question": "Type the command to rename old.txt to new.txt.",
     "choices": [], "answer": "mv old.txt new.txt",
     "explanation": "mv (move) is used both for moving files and for renaming them within the same directory."},
    {"id": "file_08", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command deletes a file?",
     "choices": ["rm", "del", "remove", "erase"], "answer": "rm",
     "explanation": "rm (remove) deletes a file. Files are NOT sent to the Trash — they're gone permanently!"},
    {"id": "file_09", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which ls option also shows hidden files?",
     "choices": ["-a", "-l", "-h", "-r"], "answer": "-a",
     "explanation": "ls -a shows files whose names start with . (hidden files). ls -la shows hidden files with details."},
    {"id": "file_10", "category": "file", "difficulty": 3, "type": "fill",
     "question": "Type the command to delete the directory 'docs' and all its contents.",
     "choices": [], "answer": "rm -r docs",
     "explanation": "rm -r (recursive) deletes a directory and everything inside it. Use rm -rf to skip confirmation."},
    {"id": "file_11", "category": "file", "difficulty": 3, "type": "choice",
     "question": "Which command finds all .log files under the current directory?",
     "choices": ["find . -name '*.log'", "ls -r *.log", "grep .log .", "search *.log"],
     "answer": "find . -name '*.log'",
     "explanation": "find searches directories recursively. -name specifies a filename pattern."},
    {"id": "file_12", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command changes file permissions?",
     "choices": ["chmod", "chown", "chgrp", "sudo"], "answer": "chmod",
     "explanation": "chmod (change mode) changes read, write, and execute permissions on a file."},
    {"id": "file_13", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command creates a symbolic link 'link.txt' pointing to 'target.txt'?",
     "choices": ["ln -s target.txt link.txt", "ln target.txt link.txt", "link -s target.txt link.txt", "mklink target.txt link.txt"],
     "answer": "ln -s target.txt link.txt",
     "explanation": "ln -s creates a symbolic link. Without -s, ln creates a hard link."},
    {"id": "file_14", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command adds execute permission to script.sh?",
     "choices": ["chmod +x script.sh", "chmod -x script.sh", "exec script.sh", "run script.sh"],
     "answer": "chmod +x script.sh",
     "explanation": "chmod +x adds execute permission. ls -l shows x in the permission string when set."},
    {"id": "file_15", "category": "file", "difficulty": 2, "type": "fill",
     "question": "Type the command to set file.txt permissions to 644 (owner: read/write; others: read only).",
     "choices": [], "answer": "chmod 644 file.txt",
     "explanation": "Octal notation: 4=read, 2=write, 1=execute. 644 = rw-r--r--."},
    {"id": "file_16", "category": "file", "difficulty": 2, "type": "fill",
     "question": "Type the command to change the owner of file.txt to alice.",
     "choices": [], "answer": "chown alice file.txt",
     "explanation": "chown (change owner) changes the owner of a file. chown alice:staff also sets the group."},
    {"id": "file_17", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command compresses the directory project/ into a tar.gz archive?",
     "choices": ["tar -czf project.tar.gz project/", "tar -xzf project.tar.gz", "gzip -r project/", "zip project.tar.gz project/"],
     "answer": "tar -czf project.tar.gz project/",
     "explanation": "tar: c=create, z=gzip compression, f=filename. Use -x (extract) to unpack."},
    {"id": "file_18", "category": "file", "difficulty": 2, "type": "fill",
     "question": "Type the command to extract backup.tar.gz into the current directory.",
     "choices": [], "answer": "tar -xzf backup.tar.gz",
     "explanation": "tar -xzf: x=extract, z=gzip, f=filename. Add -C dir/ to extract into a specific directory."},
    {"id": "file_19", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command compresses file.txt with gzip?",
     "choices": ["gzip file.txt", "compress file.txt", "pack file.txt", "zip file.txt"], "answer": "gzip file.txt",
     "explanation": "gzip compresses a file and creates file.txt.gz. The original is removed. Use gunzip to decompress."},
    {"id": "file_20", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command shows the differences between two files?",
     "choices": ["diff file1.txt file2.txt", "cmp file1.txt file2.txt", "comp file1.txt file2.txt", "compare file1.txt file2.txt"],
     "answer": "diff file1.txt file2.txt",
     "explanation": "diff shows line-by-line differences. diff -u shows unified format (like git diff)."},
    {"id": "file_21", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command shows the disk usage of the current directory in human-readable form?",
     "choices": ["du -sh .", "df -h .", "ls -sh", "stat ."], "answer": "du -sh .",
     "explanation": "du (disk usage): -s shows totals only, -h shows sizes in KB/MB/GB. du -sh * lists each item."},
    {"id": "file_22", "category": "file", "difficulty": 1, "type": "choice",
     "question": "Which command checks the free space on mounted filesystems?",
     "choices": ["df -h", "du -h", "free -h", "lsblk"], "answer": "df -h",
     "explanation": "df (disk free) shows total, used, and available space. -h gives human-readable sizes."},
    {"id": "file_23", "category": "file", "difficulty": 3, "type": "fill",
     "question": "Type the command to sync local src/ to user@server:/backup/ using rsync.",
     "choices": [], "answer": "rsync -av src/ user@server:/backup/",
     "explanation": "rsync -av: a=archive mode (preserves permissions/timestamps), v=verbose. Only changed files are transferred."},
    {"id": "file_24", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command determines the type of a file (text, binary, script, etc.)?",
     "choices": ["file script.sh", "type script.sh", "stat script.sh", "info script.sh"], "answer": "file script.sh",
     "explanation": "The file command identifies file types without relying on the extension."},
    {"id": "file_25", "category": "file", "difficulty": 3, "type": "choice",
     "question": "Which command shows detailed metadata including inode number and timestamps?",
     "choices": ["stat file.txt", "ls -li file.txt", "info file.txt", "meta file.txt"], "answer": "stat file.txt",
     "explanation": "stat displays file metadata: size, permissions, owner, inode, access/modify/change times."},
    {"id": "file_26", "category": "file", "difficulty": 2, "type": "choice",
     "question": "Which command lists the contents of a tar.gz file without extracting it?",
     "choices": ["tar -tzf archive.tar.gz", "tar -czf archive.tar.gz", "tar -xzf archive.tar.gz", "tar -lzf archive.tar.gz"],
     "answer": "tar -tzf archive.tar.gz",
     "explanation": "tar -t (list) shows the archive contents. -z handles gzip, -f specifies the filename."},
    {"id": "file_27", "category": "file", "difficulty": 3, "type": "choice",
     "question": "Which command shows where a symbolic link points?",
     "choices": ["readlink linkname", "ls -l linkname", "stat linkname", "file linkname"], "answer": "readlink linkname",
     "explanation": "readlink prints the path the symlink points to. readlink -f resolves it to an absolute path."},

    # ══════════════════════════════════════════════════════════
    # 📝 Text Processing
    # ══════════════════════════════════════════════════════════
    {"id": "text_01", "category": "text", "difficulty": 1, "type": "choice",
     "question": "Which command displays the contents of a file?",
     "choices": ["cat", "show", "print", "read"], "answer": "cat",
     "explanation": "cat (concatenate) prints file contents to standard output."},
    {"id": "text_02", "category": "text", "difficulty": 1, "type": "choice",
     "question": "Which command shows the first 10 lines of a file?",
     "choices": ["head", "tail", "top", "first"], "answer": "head",
     "explanation": "head shows the first 10 lines by default. Use head -n 20 to specify a line count."},
    {"id": "text_03", "category": "text", "difficulty": 1, "type": "choice",
     "question": "Which command shows the last 10 lines of a file?",
     "choices": ["tail", "head", "last", "end"], "answer": "tail",
     "explanation": "tail shows the last 10 lines by default. tail -f follows a file as it grows."},
    {"id": "text_04", "category": "text", "difficulty": 1, "type": "fill",
     "question": "Type the command to search for lines containing 'error' in file.txt.",
     "choices": [], "answer": "grep error file.txt",
     "explanation": "grep searches for lines matching a pattern. Use -i for case-insensitive matching."},
    {"id": "text_05", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command lets you scroll through a text file one screen at a time?",
     "choices": ["less", "cat", "more", "view"], "answer": "less",
     "explanation": "less is a pager. It's more capable than more: you can scroll up and down, and search with /."},
    {"id": "text_06", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command counts the number of lines in a file?",
     "choices": ["wc -l", "count -l", "ls -l", "cat -n"], "answer": "wc -l",
     "explanation": "wc (word count) with -l counts lines. -w counts words, -c counts bytes."},
    {"id": "text_07", "category": "text", "difficulty": 2, "type": "fill",
     "question": "Type the sed command to replace 'foo' with 'bar' everywhere in file.txt.",
     "choices": [], "answer": "sed 's/foo/bar/g' file.txt",
     "explanation": "sed's s/old/new/g replaces all occurrences on each line. Without g, only the first match is replaced."},
    {"id": "text_08", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command sorts lines of text alphabetically?",
     "choices": ["sort", "order", "arrange", "awk"], "answer": "sort",
     "explanation": "sort sorts lines. Use -r for reverse order and -n for numeric sort."},
    {"id": "text_09", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command removes consecutive duplicate lines?",
     "choices": ["uniq", "sort -u", "unique", "dedup"], "answer": "uniq",
     "explanation": "uniq removes adjacent duplicate lines. Pair it with sort to remove all duplicates."},
    {"id": "text_10", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command extracts only the 2nd field from a CSV file?",
     "choices": ["cut -d',' -f2", "cat -f2", "awk -f2", "grep -f2"], "answer": "cut -d',' -f2",
     "explanation": "cut -d',' -f2 cuts the 2nd comma-separated field. -d sets the delimiter, -f sets the field number."},
    {"id": "text_11", "category": "text", "difficulty": 3, "type": "fill",
     "question": "Type the command to count lines containing 'ERROR' in log.txt (use grep and wc).",
     "choices": [], "answer": "grep ERROR log.txt | wc -l",
     "explanation": "| (pipe) passes the output of grep as input to wc -l."},
    {"id": "text_12", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which awk command prints the 2nd space-separated field from data.csv?",
     "choices": ["awk '{print $2}' data.csv", "awk '{print $1}' data.csv", "awk -f2 data.csv", "awk 'NR==2' data.csv"],
     "answer": "awk '{print $2}' data.csv",
     "explanation": "awk's $1, $2, $3... refer to fields. $0 is the whole line. Default separator is whitespace."},
    {"id": "text_13", "category": "text", "difficulty": 2, "type": "fill",
     "question": "Type the awk command to print the 1st colon-separated field from data.csv.",
     "choices": [], "answer": "awk -F':' '{print $1}' data.csv",
     "explanation": "awk's -F option sets the field separator. Use -F',' for CSV, -F':' for colon-separated data."},
    {"id": "text_14", "category": "text", "difficulty": 3, "type": "choice",
     "question": "Which awk command skips the header row and prints only data rows?",
     "choices": ["awk 'NR>1' file.csv", "awk 'NR==1' file.csv", "awk 'skip 1' file.csv", "awk '{skip first}' file.csv"],
     "answer": "awk 'NR>1' file.csv",
     "explanation": "NR is the current record (line) number. NR>1 processes lines from row 2 onward."},
    {"id": "text_15", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command converts lowercase letters to uppercase?",
     "choices": ["echo 'hello' | tr 'a-z' 'A-Z'", "echo 'hello' | upper", "echo 'hello' | awk '{toupper}'", "echo 'hello' | sed upper"],
     "answer": "echo 'hello' | tr 'a-z' 'A-Z'",
     "explanation": "tr (translate) performs one-to-one character substitution."},
    {"id": "text_16", "category": "text", "difficulty": 2, "type": "fill",
     "question": "Type the command to delete all newline characters (\\n) from text (use tr).",
     "choices": [], "answer": "tr -d '\\n'",
     "explanation": "tr -d deletes the specified characters. Removing newlines joins all lines into one."},
    {"id": "text_17", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command passes find output to grep for a bulk search?",
     "choices": ["find . -name '*.txt' | xargs grep 'word'", "find . -name '*.txt' | grep 'word'", "find . -name '*.txt' -grep 'word'", "xargs find . -name '*.txt' grep 'word'"],
     "answer": "find . -name '*.txt' | xargs grep 'word'",
     "explanation": "xargs reads from stdin and uses the input as arguments for another command."},
    {"id": "text_18", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command saves output to a file while also displaying it on screen?",
     "choices": ["tee", "cat", "pipe", "dual"], "answer": "tee",
     "explanation": "tee writes to both stdout and a file simultaneously. Example: command | tee output.txt"},
    {"id": "text_19", "category": "text", "difficulty": 3, "type": "fill",
     "question": "Type the command to save ls output to output.txt while also showing it on screen (use tee).",
     "choices": [], "answer": "ls | tee output.txt",
     "explanation": "ls | tee output.txt displays ls output and simultaneously saves it to output.txt."},
    {"id": "text_20", "category": "text", "difficulty": 1, "type": "choice",
     "question": "Which key goes back one page in less?",
     "choices": ["b", "p", "u", "↑"], "answer": "b",
     "explanation": "In less: b goes back, Space goes forward, / searches, n jumps to next match, q quits."},
    {"id": "text_21", "category": "text", "difficulty": 3, "type": "choice",
     "question": "Which awk command sums all values in a file (one number per line)?",
     "choices": ["awk '{sum+=$1} END{print sum}' file.txt", "awk '{sum=$1} print sum' file.txt", "awk 'sum($1)' file.txt", "awk '{total $1}' file.txt"],
     "answer": "awk '{sum+=$1} END{print sum}' file.txt",
     "explanation": "The END block runs after all lines are processed. sum+=$1 accumulates the total."},
    {"id": "text_22", "category": "text", "difficulty": 3, "type": "choice",
     "question": "Which command merges two files side by side (column by column)?",
     "choices": ["paste file1.txt file2.txt", "cat file1.txt file2.txt", "join file1.txt file2.txt", "merge file1.txt file2.txt"],
     "answer": "paste file1.txt file2.txt",
     "explanation": "paste joins files horizontally (by column). cat joins them vertically (by row)."},
    {"id": "text_23", "category": "text", "difficulty": 2, "type": "choice",
     "question": "Which command shows a file with line numbers prepended?",
     "choices": ["nl file.txt", "cat -n file.txt", "num file.txt", "line file.txt"], "answer": "nl file.txt",
     "explanation": "nl (number lines) adds line numbers. cat -n does the same but nl skips blank lines by default."},
    {"id": "text_24", "category": "text", "difficulty": 3, "type": "fill",
     "question": "Type the pipeline to extract ERROR lines from log.txt and sort by frequency (most common first).",
     "choices": [], "answer": "grep ERROR log.txt | sort | uniq -c | sort -rn",
     "explanation": "grep → sort → uniq -c (count occurrences) → sort -rn (reverse numeric) is the classic frequency analysis pipeline."},

    # ══════════════════════════════════════════════════════════
    # ⚙️  Process Management
    # ══════════════════════════════════════════════════════════
    {"id": "proc_01", "category": "process", "difficulty": 1, "type": "choice",
     "question": "Which command lists currently running processes?",
     "choices": ["ps", "ls", "top", "jobs"], "answer": "ps",
     "explanation": "ps (process status) lists running processes. ps aux shows all processes with details."},
    {"id": "proc_02", "category": "process", "difficulty": 1, "type": "choice",
     "question": "Which command monitors CPU and memory usage in real time?",
     "choices": ["top", "ps", "htop", "watch"], "answer": "top",
     "explanation": "top shows process state in real time. Press q to quit."},
    {"id": "proc_03", "category": "process", "difficulty": 1, "type": "fill",
     "question": "Type the command to terminate the process with PID 1234.",
     "choices": [], "answer": "kill 1234",
     "explanation": "kill sends a signal to a process by PID. The default signal is SIGTERM (graceful stop)."},
    {"id": "proc_04", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command forcefully kills all processes named 'python'?",
     "choices": ["killall python", "kill python", "stop python", "end python"], "answer": "killall python",
     "explanation": "killall sends a signal to all processes with a given name. Use -9 for SIGKILL (force kill)."},
    {"id": "proc_05", "category": "process", "difficulty": 2, "type": "choice",
     "question": "How do you run a command in the background?",
     "choices": ["Append & to the end of the command", "Prepend bg to the command", "Press Ctrl+B", "Append # to the end of the command"],
     "answer": "Append & to the end of the command",
     "explanation": "command & runs it in the background. Use fg to bring it back to the foreground."},
    {"id": "proc_06", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which key combination suspends the current foreground process?",
     "choices": ["Ctrl+Z", "Ctrl+C", "Ctrl+S", "Ctrl+D"], "answer": "Ctrl+Z",
     "explanation": "Ctrl+Z suspends the process (SIGTSTP). Use bg to resume it in the background."},
    {"id": "proc_07", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command lists background jobs in the current shell?",
     "choices": ["jobs", "ps", "bg", "top"], "answer": "jobs",
     "explanation": "jobs shows background jobs for the current shell. Use fg %1 to bring job 1 to the foreground."},
    {"id": "proc_08", "category": "process", "difficulty": 3, "type": "fill",
     "question": "Type the command to find the PID of the process named 'nginx' (use pgrep).",
     "choices": [], "answer": "pgrep nginx",
     "explanation": "pgrep searches for processes by name and returns their PIDs."},
    {"id": "proc_09", "category": "process", "difficulty": 3, "type": "choice",
     "question": "Which command keeps a process running after the terminal is closed?",
     "choices": ["nohup", "disown", "bg", "screen"], "answer": "nohup",
     "explanation": "nohup makes a process ignore the HUP signal, so it keeps running when the terminal closes."},
    {"id": "proc_10", "category": "process", "difficulty": 2, "type": "choice",
     "question": "What is the name of the signal sent by kill -9?",
     "choices": ["SIGKILL", "SIGTERM", "SIGHUP", "SIGSTOP"], "answer": "SIGKILL",
     "explanation": "SIGKILL cannot be ignored or caught by a process — it's an immediate forced termination. SIGTERM (15) is a polite stop request."},
    {"id": "proc_11", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command sets up a scheduled recurring task?",
     "choices": ["crontab -e", "at -e", "schedule -e", "timer -e"], "answer": "crontab -e",
     "explanation": "crontab -e opens your crontab for editing. -l lists it, -r removes it."},
    {"id": "proc_12", "category": "process", "difficulty": 3, "type": "choice",
     "question": "Which cron syntax runs a script every day at 3 AM?",
     "choices": ["0 3 * * * /path/script.sh", "3 0 * * * /path/script.sh", "* * 3 * * /path/script.sh", "0 * 3 * * /path/script.sh"],
     "answer": "0 3 * * * /path/script.sh",
     "explanation": "Cron format: min hr day month weekday command. 0 3 * * * runs at 3:00 AM every day."},
    {"id": "proc_13", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command starts a command with lower priority (nice value +10)?",
     "choices": ["nice -n 10 command", "nice +10 command", "renice 10 command", "low command"],
     "answer": "nice -n 10 command",
     "explanation": "nice -n 10 starts a process at nice +10 (lower priority). Range is -20 (highest) to 19 (lowest). Root can use negative values."},
    {"id": "proc_14", "category": "process", "difficulty": 3, "type": "fill",
     "question": "Type the command to change the nice value of PID 5678 to 5.",
     "choices": [], "answer": "renice 5 5678",
     "explanation": "renice changes the nice value of a running process. Syntax: renice new_value PID."},
    {"id": "proc_15", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command shows which process has a specific file open?",
     "choices": ["lsof /path/to/file", "ps /path/to/file", "fuser /path/to/file", "open /path/to/file"],
     "answer": "lsof /path/to/file",
     "explanation": "lsof (list open files) shows processes that have a given file open. lsof -i lists network connections."},
    {"id": "proc_16", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command runs 'df -h' every 1 second and updates the display?",
     "choices": ["watch -n 1 df -h", "repeat 1 df -h", "loop -n 1 df -h", "timer 1 df -h"],
     "answer": "watch -n 1 df -h",
     "explanation": "watch -n seconds command runs a command repeatedly and refreshes the output. Ctrl+C to stop."},
    {"id": "proc_17", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command kills a command if it doesn't complete within 5 seconds?",
     "choices": ["timeout 5 command", "limit 5 command", "expire 5 command", "kill -t 5 command"],
     "answer": "timeout 5 command",
     "explanation": "timeout limits how long a command can run before being killed. Useful for preventing infinite loops in scripts."},
    {"id": "proc_18", "category": "process", "difficulty": 2, "type": "choice",
     "question": "Which command manages services (start/stop/status) on Linux?",
     "choices": ["systemctl", "service", "init", "daemon"], "answer": "systemctl",
     "explanation": "systemctl start/stop/status service-name manages services. macOS uses launchctl instead."},
    {"id": "proc_19", "category": "process", "difficulty": 3, "type": "choice",
     "question": "Which command shows which process is using port 80?",
     "choices": ["lsof -i :80", "ps -p 80", "netstat -p 80", "port -l 80"], "answer": "lsof -i :80",
     "explanation": "lsof -i :port shows the process using that port. ss -tlnp | grep 80 also works."},
    {"id": "proc_20", "category": "process", "difficulty": 3, "type": "fill",
     "question": "Type the command to run 'echo done' in 10 minutes using at.",
     "choices": [], "answer": "echo 'echo done' | at now + 10 minutes",
     "explanation": "at schedules a one-time command. You can use at now + 10 minutes, at 14:30, or at tomorrow."},

    # ══════════════════════════════════════════════════════════
    # 🌐 Networking
    # ══════════════════════════════════════════════════════════
    {"id": "net_01", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Which command tests if a host is reachable?",
     "choices": ["ping", "curl", "ssh", "traceroute"], "answer": "ping",
     "explanation": "ping sends ICMP echo requests and measures response time. Press Ctrl+C to stop."},
    {"id": "net_02", "category": "network", "difficulty": 1, "type": "fill",
     "question": "Type the command to SSH into example.com as user 'user'.",
     "choices": [], "answer": "ssh user@example.com",
     "explanation": "ssh user@hostname opens an encrypted remote login session."},
    {"id": "net_03", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Which command fetches the HTTP response from a URL?",
     "choices": ["curl", "wget", "fetch", "get"], "answer": "curl",
     "explanation": "curl sends HTTP requests and displays the response. -I for headers only, -o to save to a file."},
    {"id": "net_04", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Which command shows your network interface configuration?",
     "choices": ["ifconfig", "ipconfig", "myip", "netinfo"], "answer": "ifconfig",
     "explanation": "ifconfig shows network interface settings. On Linux, ip addr also works."},
    {"id": "net_05", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command resolves a domain name to an IP address?",
     "choices": ["nslookup", "lookup", "resolv", "host"], "answer": "nslookup",
     "explanation": "nslookup queries DNS. dig provides more detailed DNS information."},
    {"id": "net_06", "category": "network", "difficulty": 2, "type": "fill",
     "question": "Type the command to check if port 80 on example.com is open (use nc).",
     "choices": [], "answer": "nc -zv example.com 80",
     "explanation": "nc (netcat) with -z scans for open ports; -v gives verbose output."},
    {"id": "net_07", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command shows the routers (hops) a packet travels through to reach a destination?",
     "choices": ["traceroute", "ping", "route", "netstat"], "answer": "traceroute",
     "explanation": "traceroute shows each hop (router) from source to destination."},
    {"id": "net_08", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command downloads a file from a URL and saves it?",
     "choices": ["wget https://example.com/file", "curl https://example.com/file", "fetch https://example.com/file", "download https://example.com/file"],
     "answer": "wget https://example.com/file",
     "explanation": "wget downloads a file and saves it. curl -O does the same."},
    {"id": "net_09", "category": "network", "difficulty": 3, "type": "choice",
     "question": "Which command lists active TCP connections with process names?",
     "choices": ["lsof -i -P -n", "netstat -an", "ss -tlnp", "ps -net"], "answer": "lsof -i -P -n",
     "explanation": "lsof -i shows open network connections. -P shows port numbers, -n skips DNS reverse lookup."},
    {"id": "net_10", "category": "network", "difficulty": 3, "type": "fill",
     "question": "Type the command to tunnel local port 8080 to remote port 80 on srv.example.com (user: user).",
     "choices": [], "answer": "ssh -L 8080:localhost:80 user@srv.example.com",
     "explanation": "ssh -L localport:host:remoteport sets up local port forwarding."},
    {"id": "net_11", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Which modern Linux command shows IP addresses for all network interfaces?",
     "choices": ["ip addr show", "ifconfig", "netstat -i", "route -n"], "answer": "ip addr show",
     "explanation": "The ip command (iproute2) is the modern replacement for ifconfig. ip route show gives routing tables."},
    {"id": "net_12", "category": "network", "difficulty": 2, "type": "fill",
     "question": "Type the command to show the routing table including the default gateway (use ip).",
     "choices": [], "answer": "ip route show",
     "explanation": "ip route show displays the routing table. The 'default' row is the default gateway. macOS uses netstat -rn."},
    {"id": "net_13", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command displays current TCP/UDP connection states?",
     "choices": ["netstat -an", "ps -net", "lsof -net", "conn -a"], "answer": "netstat -an",
     "explanation": "netstat -an shows all connections and listening ports. -t for TCP only, -u for UDP only."},
    {"id": "net_14", "category": "network", "difficulty": 3, "type": "choice",
     "question": "Which ss command shows LISTEN TCP ports with process names?",
     "choices": ["ss -tlnp", "ss -an", "ss -tcp", "ss -listen"], "answer": "ss -tlnp",
     "explanation": "ss (socket statistics) is netstat's successor. -t=TCP, -l=LISTEN, -n=numeric, -p=process names."},
    {"id": "net_15", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command provides detailed DNS query information?",
     "choices": ["dig", "nslookup", "host", "resolve"], "answer": "dig",
     "explanation": "dig (domain information groper) shows detailed DNS records. dig +short prints only the result; dig MX checks mail servers."},
    {"id": "net_16", "category": "network", "difficulty": 2, "type": "fill",
     "question": "Type the dig command to show only the IP address(es) for google.com.",
     "choices": [], "answer": "dig +short google.com",
     "explanation": "dig +short prints only the answer (e.g., IP address). dig google.com A shows the full A record."},
    {"id": "net_17", "category": "network", "difficulty": 2, "type": "fill",
     "question": "Type the command to copy local file.txt to the home directory of user@server.com (use scp).",
     "choices": [], "answer": "scp file.txt user@server.com:~/",
     "explanation": "scp (secure copy) uses SSH for encrypted file transfer. Remote→local: scp user@host:remote_path local_path."},
    {"id": "net_18", "category": "network", "difficulty": 1, "type": "choice",
     "question": "Which command shows this machine's hostname?",
     "choices": ["hostname", "uname -n", "cat /etc/hostname", "id -h"], "answer": "hostname",
     "explanation": "hostname prints the system's hostname. hostname new-name changes it (requires admin)."},
    {"id": "net_19", "category": "network", "difficulty": 3, "type": "choice",
     "question": "Which curl command sends an HTTP POST request with a JSON body?",
     "choices": [
         "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' URL",
         "curl POST -json '{\"key\":\"val\"}' URL",
         "curl -p '{\"key\":\"val\"}' URL",
         "curl --post-json '{\"key\":\"val\"}' URL",
     ],
     "answer": "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' URL",
     "explanation": "curl -X sets the HTTP method, -H adds a header, -d sets the request body. Widely used for REST API testing."},
    {"id": "net_20", "category": "network", "difficulty": 2, "type": "choice",
     "question": "Which command generates an SSH key pair?",
     "choices": ["ssh-keygen", "keygen", "ssh -genkey", "openssl genrsa"], "answer": "ssh-keygen",
     "explanation": "ssh-keygen generates RSA or Ed25519 key pairs. Creates ~/.ssh/id_rsa (private) and id_rsa.pub (public)."},

    # ══════════════════════════════════════════════════════════
    # 🐚 Shell & Environment
    # ══════════════════════════════════════════════════════════
    {"id": "shell_01", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "Which command shows the manual page for ls?",
     "choices": ["man ls", "help ls", "ls --help", "info ls"], "answer": "man ls",
     "explanation": "man (manual) displays the manual page. Press q to quit, / to search."},
    {"id": "shell_02", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "Type the command to find the actual path of the python3 executable.",
     "choices": [], "answer": "which python3",
     "explanation": "which shows the path of a command's executable. Useful when multiple versions are installed."},
    {"id": "shell_03", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which command checks if cd is a shell built-in?",
     "choices": ["type cd", "which cd", "whereis cd", "file cd"], "answer": "type cd",
     "explanation": "type shows whether a command is a built-in, external, or alias. cd is a shell builtin."},
    {"id": "shell_04", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "Which command displays the value of the HOME environment variable?",
     "choices": ["echo $HOME", "print HOME", "env HOME", "show $HOME"], "answer": "echo $HOME",
     "explanation": "Prefix a variable name with $ to expand its value. echo $HOME, $USER, $PATH are commonly used."},
    {"id": "shell_05", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "Type the command to set MY_VAR=hello and export it to child processes.",
     "choices": [], "answer": "export MY_VAR=hello",
     "explanation": "export makes a variable available to child processes. Without export, it stays in the current shell only."},
    {"id": "shell_06", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "Which command lists all current environment variables?",
     "choices": ["env", "set", "printenv", "vars"], "answer": "env",
     "explanation": "env lists all environment variables. printenv VAR shows a single variable's value."},
    {"id": "shell_07", "category": "shell", "difficulty": 2, "type": "fill",
     "question": "Type the command to add /usr/local/bin to the end of $PATH.",
     "choices": [], "answer": "export PATH=$PATH:/usr/local/bin",
     "explanation": "To append: export PATH=$PATH:new_dir. To prepend: export PATH=new_dir:$PATH."},
    {"id": "shell_08", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which command immediately applies changes made to ~/.bashrc in the current shell?",
     "choices": ["source ~/.bashrc", "exec ~/.bashrc", "run ~/.bashrc", "bash ~/.bashrc"],
     "answer": "source ~/.bashrc",
     "explanation": "source (or .) runs a file in the current shell context. Equivalent to opening a new shell with that config."},
    {"id": "shell_09", "category": "shell", "difficulty": 1, "type": "fill",
     "question": "Type the command to create an alias 'll' that runs 'ls -la'.",
     "choices": [], "answer": "alias ll='ls -la'",
     "explanation": "alias name='command' creates an alias. Add it to ~/.bashrc or ~/.zshrc to make it permanent."},
    {"id": "shell_10", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "Which command lists all currently set aliases?",
     "choices": ["alias", "list alias", "show alias", "env alias"], "answer": "alias",
     "explanation": "Running alias without arguments lists all defined aliases. unalias name removes one."},
    {"id": "shell_11", "category": "shell", "difficulty": 1, "type": "choice",
     "question": "Which command shows your command history?",
     "choices": ["history", "last", "log", "recent"], "answer": "history",
     "explanation": "history lists previously run commands with numbers. Use !N to re-run command N."},
    {"id": "shell_12", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which shortcut re-runs the previous command?",
     "choices": ["!!", "!-1", "^r", "↑ + Enter"], "answer": "!!",
     "explanation": "!! expands to the previous command. Useful with: sudo !!"},
    {"id": "shell_13", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which variable holds the last argument of the previous command?",
     "choices": ["$_", "$$", "$!", "$#"], "answer": "$_",
     "explanation": "$_ holds the last argument of the previous command. !$ works similarly. mkdir newdir && cd $_ is a common pattern."},
    {"id": "shell_14", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which variable holds the exit status of the last command?",
     "choices": ["$?", "$!", "$$", "$0"], "answer": "$?",
     "explanation": "$? holds the exit status: 0 means success; non-zero means failure. Use in: if [ $? -eq 0 ]; then ..."},
    {"id": "shell_15", "category": "shell", "difficulty": 3, "type": "choice",
     "question": "Which variables hold the 1st and 2nd arguments passed to a shell script?",
     "choices": ["$1 and $2", "@1 and @2", "%1 and %2", "#1 and #2"], "answer": "$1 and $2",
     "explanation": "$1, $2, $3... hold positional parameters. $# is the argument count; $@ is all arguments."},
    {"id": "shell_16", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "What is the difference between single quotes (') and double quotes (\") in the shell?",
     "choices": [
         "Single quotes don't expand variables; double quotes do",
         "They are identical",
         "Single quotes expand variables; double quotes don't",
         "Single quotes are for numbers; double quotes for strings",
     ],
     "answer": "Single quotes don't expand variables; double quotes do",
     "explanation": "Single quotes treat everything literally. echo '$HOME' → $HOME. Double quotes expand variables. echo \"$HOME\" → /Users/user."},
    {"id": "shell_17", "category": "shell", "difficulty": 2, "type": "choice",
     "question": "Which glob pattern matches all .txt files in the current directory?",
     "choices": ["*.txt", "?.txt", "[.txt]", "%.txt"], "answer": "*.txt",
     "explanation": "* matches zero or more characters. ? matches exactly one. [abc] matches one of a, b, or c."},
    {"id": "shell_18", "category": "shell", "difficulty": 3, "type": "choice",
     "question": "Which shell option causes a script to exit immediately on any error?",
     "choices": ["set -e", "set -x", "set -u", "set -o"], "answer": "set -e",
     "explanation": "set -e exits the script on the first error. set -x prints each command before running it (debug mode). set -u treats unset variables as errors."},

    # ══════════════════════════════════════════════════════════
    # 💻 System Info
    # ══════════════════════════════════════════════════════════
    {"id": "sys_01", "category": "system", "difficulty": 1, "type": "choice",
     "question": "Which command shows OS name, kernel version, and hardware info all at once?",
     "choices": ["uname -a", "uname -r", "uname -s", "sysinfo"], "answer": "uname -a",
     "explanation": "uname -a (all) shows the system name, node name, kernel version, hardware type, and more."},
    {"id": "sys_02", "category": "system", "difficulty": 1, "type": "fill",
     "question": "Type the command to show only the kernel version.",
     "choices": [], "answer": "uname -r",
     "explanation": "uname -r (release) shows the kernel version. Example: 5.15.0-58-generic"},
    {"id": "sys_03", "category": "system", "difficulty": 1, "type": "choice",
     "question": "Which command shows how long the system has been running and the load average?",
     "choices": ["uptime", "top", "ps", "sysctl"], "answer": "uptime",
     "explanation": "uptime shows current time, time since last boot, number of logged-in users, and 1/5/15-min load averages."},
    {"id": "sys_04", "category": "system", "difficulty": 1, "type": "choice",
     "question": "Which command shows the current date and time?",
     "choices": ["date", "time", "clock", "now"], "answer": "date",
     "explanation": "date prints the current date and time. date +\"%Y-%m-%d %H:%M\" formats the output."},
    {"id": "sys_05", "category": "system", "difficulty": 2, "type": "fill",
     "question": "Type the date command to display today's date in YYYY-MM-DD format.",
     "choices": [], "answer": "date +%Y-%m-%d",
     "explanation": "date +format specifies the output format. %Y=4-digit year, %m=month, %d=day, %H=hour, %M=minute."},
    {"id": "sys_06", "category": "system", "difficulty": 1, "type": "choice",
     "question": "Which command lists currently logged-in users?",
     "choices": ["who", "users", "id", "last"], "answer": "who",
     "explanation": "who shows logged-in users, their terminal, and login time. w shows more detail including their current command."},
    {"id": "sys_07", "category": "system", "difficulty": 1, "type": "choice",
     "question": "Which command shows the current user's UID, GID, and groups?",
     "choices": ["id", "who", "whoami", "groups"], "answer": "id",
     "explanation": "id shows UID, GID, and group memberships. uid=0(root) means you're root."},
    {"id": "sys_08", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Which command shows logged-in users and what command they're running?",
     "choices": ["w", "who", "ps", "top"], "answer": "w",
     "explanation": "w shows more detail than who: it includes each user's current command and the load average."},
    {"id": "sys_09", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Which command shows disk space usage for all filesystems in human-readable form?",
     "choices": ["df -h", "du -h", "lsblk", "fdisk -l"], "answer": "df -h",
     "explanation": "df -h shows total, used, and available space for each filesystem. -T also shows the filesystem type."},
    {"id": "sys_10", "category": "system", "difficulty": 2, "type": "fill",
     "question": "Type the command to show the size of each file and directory in the current directory (use du).",
     "choices": [], "answer": "du -sh *",
     "explanation": "du -sh * shows the size of each item. -s shows totals only; -h shows human-readable sizes."},
    {"id": "sys_11", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Which Linux command checks memory usage?",
     "choices": ["free -h", "mem -h", "vmstat -h", "top -m"], "answer": "free -h",
     "explanation": "free -h shows total, used, and free memory. macOS uses vm_stat or top instead."},
    {"id": "sys_12", "category": "system", "difficulty": 3, "type": "choice",
     "question": "Which command shows the kernel ring buffer (boot messages, device errors)?",
     "choices": ["dmesg", "syslog", "journalctl", "klog"], "answer": "dmesg",
     "explanation": "dmesg shows kernel messages. dmesg | tail shows recent entries like USB events or driver errors."},
    {"id": "sys_13", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Which Linux file contains CPU model name and core count information?",
     "choices": ["/proc/cpuinfo", "/sys/cpu/info", "/dev/cpu", "/etc/cpuinfo"], "answer": "/proc/cpuinfo",
     "explanation": "cat /proc/cpuinfo shows CPU details. On macOS use: sysctl -n machdep.cpu.brand_string"},
    {"id": "sys_14", "category": "system", "difficulty": 3, "type": "choice",
     "question": "Which command reads and modifies kernel parameters?",
     "choices": ["sysctl", "syscfg", "kparam", "modprobe"], "answer": "sysctl",
     "explanation": "sysctl -a lists all kernel parameters. sysctl -w key=value changes them (requires root). Works on both macOS and Linux."},
    {"id": "sys_15", "category": "system", "difficulty": 2, "type": "choice",
     "question": "Which Linux file shows the OS distribution name and version?",
     "choices": ["/etc/os-release", "/etc/version", "/proc/version", "/etc/distro"], "answer": "/etc/os-release",
     "explanation": "cat /etc/os-release shows the distro name and version (Ubuntu, Debian, CentOS, etc.). lsb_release -a also works."},
]
